#!/usr/bin/expect -f
set DOWN \x1B\[B;
cd /usr/local/yeoman/SonataBSS
spawn yo angular-crud-custom-module
expect "========================================================================== (Y/n)"
send "n\r"
expect "Enter your project name?"
send "SonataBSS\r" 
expect ":/usr/local/yeoman/SonataBSS$ "
spawn yo angular-crud-custom-module:module
expect "Enter your module name?"
send "nSD\r" 
expect "Where would you like to create this module?"
send "app/modules/NSD\r" 
expect "Would you like to create field?" 
send "Y\r"
expect "radio" 
send "$DOWN$DOWN\r"
expect "Please enter label:key required for this field..Ex(First Name:fName:true).." 
send "Id:id:true\r"
expect "Would you like to create field" 
send "Y\r"
expect "Please select field.. (Use arrow keys)" 
send "$DOWN$DOWN\r"
expect "Please enter label:key required for this field..Ex(First Name:fName:true).." 
send "Name:name:true\r"
expect "Would you like to create field" 
send "Y\r"
expect "Please select field.. (Use arrow keys)" 
send "$DOWN$DOWN\r"
expect "Please enter label:key required for this field..Ex(First Name:fName:true).." 
send "Vendor:vendor:true\r"
expect "Would you like to create field" 
send "Y\r"
expect "Please select field.. (Use arrow keys)" 
send "$DOWN$DOWN\r"
expect "Please enter label:key required for this field..Ex(First Name:fName:true).." 
send "Version:version:true\r"
expect "Would you like to create field" 
send "N\r"
expect "Overwrite app\app.js?" 
send "a\r"
expect "$ "
spawn yo angular-crud-custom-module:module
expect "Enter your module name?"
send "InstantiationRequests\r" 
expect "Where would you like to create this module?"
send "app/modules/InstantiationRequests\r" 
expect "Would you like to create field?" 
send "Y\r"
expect "radio" 
send "$DOWN$DOWN\r"
expect "Please enter label:key required for this field..Ex(First Name:fName:true).." 
send "Id:id:true\r"
expect "Would you like to create field" 
send "Y\r"
expect "Please select field.. (Use arrow keys)" 
send "$DOWN$DOWN\r"
expect "Please enter label:key required for this field..Ex(First Name:fName:true).." 
send "Name:name:true\r"
expect "Would you like to create field" 
send "Y\r"
expect "Please select field.. (Use arrow keys)" 
send "$DOWN$DOWN\r"
expect "Please enter label:key required for this field..Ex(First Name:fName:true).." 
send "Vendor:vendor:true\r"
expect "Would you like to create field" 
send "Y\r"
expect "Please select field.. (Use arrow keys)" 
send "$DOWN$DOWN\r"
expect "Please enter label:key required for this field..Ex(First Name:fName:true).." 
send "Version:version:true\r"
expect "Would you like to create field" 
send "N\r"
expect "Overwrite app\app.js?" 
send "a\r"
expect "$ "
